To be edited
Nicanor008/shoman-FE pull request #49
Opened 2020-12-11 12:51 UTC by Nyakaru

- PR is up for easier tracking of files

2020-12-11 16:32 UTC, Nicanor008 commented
ncie, will review ongoing and give feedback where necessary on weekend

2020-12-17 05:18 UTC, Nicanor008 requested changes
Good work @Nyakaru, you've done quite awesome stuff here

2020-12-17 05:18 UTC, Nicanor008 commented on src/components/auth/login/login.js
> +    }
This block will fail in prod since gatsby doesn't have access to window events and will give window undefined error. Not sure locally but you can try to `gatsby build` to see if the error is there.
To solve wrap in an if statement 
```
if (typeof window !== "undefined") {
 // localstorage code 
}
```

2020-12-17 05:18 UTC, Nicanor008 commented on src/components/auth/signup/signup.js
> +      if ( password != pass ) {
use strict operator `===`

2020-12-17 05:18 UTC, Nicanor008 commented on src/components/auth/signup/signup.js
> +  const [passErrors, setPassErrors] = useState(null)
Just to keep in mind.

it's always unsafe in frontend to show specific error in login, exposes security, like telling user wrong email  only, good to generalize, like incorrect login credentials.

For now implementation is okay, but for future systems

2020-12-17 05:18 UTC, Nicanor008 commented on src/utils/helpers/toaster.js
> +        position: toast.POSITION.TOP_RIGHT,
we could use the same position for all toast notifications.

2020-12-17 05:58 UTC, Nicanor008 requested changes

2020-12-17 05:58 UTC, Nicanor008 commented on src/hoc/requiresAuth.js
> +  }, [])
if this is on component on mount only, then remove dependency array
```suggestion
  useEffect(() => {
    ensureAuth()
  })
```

2021-01-05 15:03 UTC, Nicanor008 commented
@Nyakaru is this ready for merging or you still working on it?

2021-01-06 06:02 UTC, Nyakaru commented
> @Nyakaru is this ready for merging or you still working on it?

Hey, @Nicanor008 It is not ready yet. There is a lot on my plate right now. The earliest I can look at this is during the weekend, or someone can take it up and complete

2021-01-07 08:22 UTC, Nicanor008 commented
> > @Nyakaru is this ready for merging or you still working on it?
> 
> Hey, @Nicanor008 It is not ready yet. There is a lot on my plate right now. The earliest I can look at this is during the weekend, or someone can take it up and complete

ok, I'll pick this today as I've some free time.

2021-01-09 15:54 UTC, closed without merging